export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'Arial, sans-serif', margin: 0, padding: 0, height: '100vh', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
        {children}
        <footer style={{ padding: '1rem', backgroundColor: '#f5f5f5' }}>
          <p>&copy; 2025 My App</p>
        </footer>
      </body>
    </html>
  )
}
