import Link from "next/link"

export const metadata = {
  title: {
    default: 'My App', // This is for the root page
    template: '%s | My App', // This is for children pages
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between', fontFamily: 'Arial, sans-serif', margin: 0, padding: 0, height: '100vh' }}>
        <header style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '1rem', backgroundColor: '#f5f5f5' }}>
          <h1>My App</h1>
          <nav>
            <ul>
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/products">Products</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        <footer style={{ padding: '1rem', backgroundColor: '#f5f5f5' }}>
          <p>&copy; 2025 My App</p>
        </footer>
      </body>
    </html>
  )
}
