import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'Arial, sans-serif', margin: 0, padding: 0, height: '100vh', display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
        <header style={{ display: 'flex', justifyContent: 'space-between', padding: '1rem', backgroundColor: '#f5f5f5' }}>
          <h1>My App</h1>
          <nav>
            <ul className="flex gap-4">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/customers">Customers</Link>
              </li>
              <li>
                <Link href="/revenue">Revenue</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        <footer style={{ padding: '1rem', backgroundColor: '#f5f5f5' }}>
          <p>&copy; 2025 My App</p>
        </footer>
      </body>
    </html>
  )
}
